name: Smart Contract CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        run: |
         curl -L https://foundry.paradigm.xyz | bash
         ~/.foundry/bin/foundryup
         echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Build
        run: forge build

      - name: Test
        run: forge test --gas-report || true