name: Smart Contract CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check forge
        run: forge --version

      - name: Build
        run: forge build

      - name: Test
        run: forge test --gas-report || true